apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jira
  region: ap-northeast-1

nodeGroups:
- name: ng-worker-addon-test
  availabilityZones: ["ap-northeast-1a", "ap-northeast-1d"] ##Certain VPC Subnet
  labels: { role: workers }
  privateNetworking: true
  volumeSize: 100
  volumeType: gp2
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
  amiFamily: AmazonLinux2
  ssh:
    allow: true #Default
    publicKeyName: keypair #Exist Keypair
  iam:
    withAddonPolicies:
      albIngress: true
      cloudWatch: true
      autoScaler: true
      externalDNS: true
      certManager: true
#      appMesh: true
  instancesDistribution:
    maxPrice: 0.035
    instanceTypes: ["m5a.xlarge","m5a.2xlarge"] # At least one instance type should be specified
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 0
