apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-jira
  region: ap-northeast-1

nodeGroups:
  - name: ng-worker-db
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    minSize: 1
    maxSize: 1
    iam:
      withAddonPolicies:
        externalDNS: true
        imageBuilder: true
        autoScaler: false
        certManager: false
        appMesh: true
        ebs: true
        fsx: false
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
