apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jira-app
  region: ap-northeast-1

managedNodeGroups:
  - name: ng-worker-logging
    labels: { role: workers }
    instanceType: t3a.large	
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    minSize: 1
    maxSize: 1
    ssh:
      allow: true #Default
      publicKeyName: keypair #Exist Keypair
    iam:
      withAddonPolicies:
        externalDNS: true
        imageBuilder: true
        autoScaler: false
        certManager: false
        appMesh: true
        ebs: true
        fsx: false
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
