apiVersion: v1
kind: Service
metadata:
  namespace: work
  name: postgressvc
  labels:
    app: postgressvc
spec:
  type: NodePort
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: work
  name: postgres
spec:
  serviceName: postgressvc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        envFrom:
          - configMapRef:
              name: postgres-configmap
          - secretRef:
              name: postgres-secret
        ports:
        - containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name	
                operator: In
                values:
                - ng-worker-db 
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp2
      resources:
        requests:
          storage: 50Gi
