apiVersion: v1
kind: ConfigMap
metadata:
  namespace: work
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: jiradb
  POSTGRES_USER: admin

---
apiVersion: v1
kind: Secret
metadata:
  namespace: work
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
