apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-alb
  namespace: work 
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    external-dns.alpha.kubernetes.io/hostname: jira.rayhli.com
#    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: instance
#    alb.ingress.kubernetes.io/healthcheck-path: '/'
  labels:
    app: jira-argocd-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: jira-svc
          servicePort: 80
