apiVersion: v1
kind: Service
metadata:
  namespace: work
  name: jira-svc
  labels:
    app: jira-dev
spec:
  selector:
    app: jira 
  ports:
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: http
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  namespace: work
  name: confluence-svc
  labels:
    app: confluence-dev
spec:
  selector:
    app: confluence
  ports:
 # - name: https
 #   protocol: TCP
 #   port: 443
 #   targetPort: http
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  type: NodePort
