apiVersion: v1
kind: ConfigMap
metadata:
  namespace: work
  name: postgres-configmap-conf
  labels:
    app: postgres
data:
  POSTGRES_DB: jiradb
  POSTGRES_USER: admin

---
apiVersion: v1
kind: Secret
metadata:
  namespace: work
  name: postgres-secret-conf
  labels:
    app: postgres
type: Opaque
data:
#  POSTGRES_DB: amlyYWRi
#  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
